# Generated by Django 5.0.6 on 2024-05-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("To Duy Nguyen Hoang", "To Duy Nguyen Hoang"),
                            ("To Duy Chau", "To Duy Chau"),
                            ("Tran Thi Huong", "Tran Thi Huong"),
                            ("Ho Thi Khuyen", "Ho Thi Khuyen"),
                            ("To Thanh Thao", "To Thanh Thao"),
                            ("To Huong Giang", "To Huong Giang"),
                            ("Tran Duc Bo", "Tran Duc Bo"),
                            ("Kha Banh", "Kha Banh"),
                            ("Mokey D Luffy", "Monkey D Luffy"),
                            ("Roronoa Zoro", "Roronoa Zoro"),
                            ("BTS", "BTS"),
                            ("Lee JooBin", "Lee JooBin"),
                            ("Choi YiKyung", "Choi YiKyung"),
                            ("Black Goku", "Black Goku"),
                            ("Nguyen Quang Vu", "Nguyen Quang Vu"),
                            ("Truong My Lan", "Truong My Lan"),
                            ("Huan Hoa Hong", "Huan Hoa Hong"),
                            ("Sukuna", "Sukuna"),
                            ("Go/jo", "Go/jo"),
                            ("Bac Ho", "Bac Ho"),
                            ("Vergil", "Vergil"),
                            ("Dante", "Dante"),
                            ("Sephiroth", "Sephiroth"),
                            ("Cong Don Thuy Te", "Cong Don Thuy Te"),
                            ("Dog China", "Dog China"),
                            ("Ma Vuong Tulen", "Ma Vuong Tulen"),
                            ("Jack 5 cu", "Jack 5 cu"),
                            ("Thang Bo Con", "Thang Bo Con"),
                            ("Kim SeokJin", "Kim SeokJin"),
                            ("Kim Taehyung", "Kim Taehyung"),
                            ("Phat To Nhu Lai", "Phat To Nhu Lai"),
                            ("Ton Ngo Khong", "Ton Ngo Khong"),
                            ("Viet Nam", "Viet Nam"),
                            ("Le Dao Xuan Thanh", "Le Dao Xuan Thanh"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
