# Generated by Django 5.0.6 on 2024-05-20 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("Alabama", "Alabama"),
                    ("Alaska", "Alaska"),
                    ("Arizona", "Arizona"),
                    ("Arkansas", "Arkansas"),
                    ("California", "California"),
                    ("Colorado", "Colorado"),
                    ("Connecticut", "Connecticut"),
                    ("Delaware", "Delaware"),
                    ("Florida", "Florida"),
                    ("Georgia", "Georgia"),
                    ("Hawaii", "Hawaii"),
                    ("Idaho", "Idaho"),
                    ("Illinois", "Illinois"),
                    ("Indiana", "Indiana"),
                    ("Iowa", "Iowa"),
                    ("Kansas", "Kansas"),
                    ("Kentucky", "Kentucky"),
                    ("Louisiana", "Louisiana"),
                    ("Maine", "Maine"),
                    ("Maryland", "Maryland"),
                    ("Massachusetts", "Massachusetts"),
                    ("Michigan", "Michigan"),
                    ("Minnesota", "Minnesota"),
                    ("Mississippi", "Mississippi"),
                    ("Missouri", "Missouri"),
                    ("Montana", "Montana"),
                    ("Nebraska", "Nebraska"),
                    ("Nevada", "Nevada"),
                    ("New Hampshire", "New Hampshire"),
                    ("New Jersey", "New Jersey"),
                    ("New Mexico", "New Mexico"),
                    ("New York", "New York"),
                    ("North Carolina", "North Carolina"),
                    ("North Dakota", "North Dakota"),
                    ("Ohio", "Ohio"),
                    ("Oklahoma", "Oklahoma"),
                    ("Oregon", "Oregon"),
                    ("Pennsylvania", "Pennsylvania"),
                    ("Rhode Island", "Rhode Island"),
                    ("South Carolina", "South Carolina"),
                    ("South Dakota", "South Dakota"),
                    ("Tennessee", "Tennessee"),
                    ("Texas", "Texas"),
                    ("Utah", "Utah"),
                    ("Vermont", "Vermont"),
                    ("Virginia", "Virginia"),
                    ("Washington", "Washington"),
                    ("West Virginia", "West Virginia"),
                    ("Wisconsin", "Wisconsin"),
                    ("Wyoming", "Wyoming"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
